import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body className="border-2 w-[768px] h-[1024px]">{children}</body>
    </html>
  );
}
